services:
  - type: web
    name: quickcargo-webhook
    runtime: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python webhook_server.py
